crawl:
	scrapy crawl extension_detail -L WARNING



shell:
	https_proxy=http://127.0.0.1:7890 scrapy shell "https://chromewebstore.google.com/detail/meeting-assistant-chatgpt/kdkohcmkkplmkknlelglhfhjkegkiljd"